### ISSUE TITLE
[15660:10932:0420/024221.053:ERROR:device_event_log_impl.cc(195)] [02:42:21.053] Bluetooth: bluetooth_adapter_winrt.cc:1057 Getting Default Adapter failed.

### ISSUE THREAD

**Issue by Tylcha** [david96182/ninjemail#1]
Hey man, thanks your project, very helpful me, i havent bluetoth adaptor.Add to line chrome drivers 
options.add_experimental_option('excludeSwitches',['enable-logging'])
i dont try firefox.

**Comment by david96182** [comment]
Thanks for reaching out!

I'm glad you find the project helpful.

- Chrome Driver Option: Thanks for letting me know about the excludeSwitches option for Chrome drivers. I'll analyze its impact on logging behavior and consider including it with proper documentation.
- Testing Firefox: While you haven't tried Firefox yet, testing across different browsers is a great practice. The project likely includes a function like create_driver('firefox') for launching Firefox. You can explore adding similar test cases for Firefox alongside Chrome.

Next Steps:

I'll analyze the excludeSwitches option and its implications for logging.
I'll consider adding documentation for this option if it proves beneficial.
I would recommend trying the project with Firefox as well. If you encounter any issues, feel free to open a new issue or reach out for help.
