### ISSUE TITLE
Fix for captchas not working.

### ISSUE THREAD

**Issue by RobBlume** [david96182/ninjemail#7]
Bug#1
File name - 
webdriver_utils.py

Line# 22
with open(file_path, 'w', encoding='utf-8',newline='\n') as file:

W/o this fix chrome will launch and capsolver has no api key.

Bug#2
File name -
\captcha_solvers\capsolver-chrome-extension\assets\config.js

When running the pytest command you are setting the value of apiKey to a value that breaks. i couldnt get the solver to work until i reset apikey back to ''

Here is an example of what it looked like.
apiKey: 'Actual-Capsolver-Key'token': 'aaaaaaaa'}'token': 'aaaaaaaa'}'token': 'aaaaaaaa'}'token': 'aaaaaaaa'}'token': 'aaaaaaaa'}'token': 'aaaaaaaa'}'token': 'aaaaaaaa'}',

**Comment by david96182** [comment]
Thank you for reporting these issues! I appreciate your contribution to improving the repository. I was aware of these problems. The first one is only happening on Windows, but I haven't had the time to work on it. I will test your fix and apply it if it works.

**Comment by RobBlume** [comment]
I noticed with yahoo the getsms function is also pulling the area code(+1) even though you call the function specifying for it to not return the area code.

**Comment by david96182** [comment]
To ensure optimal results for Gmail registrations, I would recommend using undetected-chrome instead of the regular Chrome variant of the Chrome driver.
> Is the regular chrome variant of chrome driver detected by google? or do i need to use undetected-chrome for gmail registrations to work.

**Comment by david96182** [comment]
If the problem persists, please create a new issue. I have not received any reports about this issue, and it is working fine based on my testing.
> I noticed with yahoo the getsms function is also pulling the area code(+1) even though you call the function specifying for it to not return the area code.

I have pushed changes that address the initial issues reported in this thread, so I am closing this issue.
