### ISSUE TITLE
Why is CapSolver so expensive.

### ISSUE THREAD

**Issue by BeeperMiniSourceCode** [david96182/ninjemail#8]
How am I supposed to use CapSolver if the prices for FunCaptcha is $200-300.

**Comment by david96182** [comment]
This is not a bug or related issue. It would be more suitable for discussions or the community forum. Nevertheless, I am unsure where you checked the price. According to the official capsolver documentation, the pricing for FunCaptcha is as follows: 'FunCaptcha **$1.6/1000 requests** **$0.6/1000 images**'.
